"""Rows, scores and verdicts of the ADM semantic conformance matrix.

Judgements of the 2026-09-11 audit.  Numbers inside ``{}`` are substituted by
``build_matrix.py`` from the evidence files, so the wording never carries a
figure the evidence does not.  Evidence file names are relative to
``docs/audit/evidence/adm/``.
"""

E = {
    "pcm": "adm-object-pcm-compare.json", "map": "adm-track-mapping.json", "ref": "adm-reference-graph.json", "time": "adm-event-timing.json",
    "coord": "adm-coordinate-diff.json", "interp": "adm-interpolation-diff.json", "gain": "adm-gain-diff.json", "har": "adm-harness.json",
    "dolby": "adm-dolby-reference.json", "neg": "adm-negative-controls.json", "cont": "adm-container-validation.json", "rend": "adm-render-comparison.json",
    "long": "adm-long-duration.json", "spec": "01-spec-extracts.json", "prov": "00-provenance.json", "batch": "adm-batch-summary.json",
}

ROWS = [
    dict(feature="Object PCM", source="TrueHD object-presentation channels / JOC reconstructed object signals", internal="`Vec<i32>` rows per frame, element order", damf="CAF 24-bit BE, one channel per element", adm="`data` chunk 24-bit LE, one track per element",
         evidence=f"{E['pcm']}, {E['long']}", cls="MEASURED", structural="PASS", semantic="PASS", classification="sample-exact",
         note="{pcm_identical} of {pcm_pairs} declared DAMF/ADM track pairs are sample-identical (SHA-256 of the samples equal) over {inputs} inputs including the whole-film Pi ({full_frames} frames); the full pairing matrix confirms every declared pair ({matrix_confirmed_all}). The ADM carries exactly the PCM the decoder produced; JOC objects are the decoder's reconstruction, not the master (differential claim)."),
    dict(feature="Bed PCM and LFE", source="OAMD bed channels (corpus: LFE only)", internal="bed slots, conformed to 7.1.2 by default", damf="bed channels first", adm="DirectSpeakers tracks first, `RC_*` labels",
         evidence=f"{E['pcm']}, {E['har']} (C21, C21b)", cls="MEASURED", structural="PASS", semantic="PASS", classification="label-confirmed",
         note="LFE is sample-identical in every input; harness C21 codes the bed as Rss, Lss, LFE and the tones land under the matching labels with conform on ({c21_tones}) and off. LFE is identified only by the `RC_LFE` label and position [-1,1,-1] (profile table 10); a BS.2127 renderer does not recognise that label (EAR warning) - a profile-level interoperability limit shared with Dolby's own files."),
    dict(feature="Channel assignment / track mapping", source="element order: beds, ISF, dynamic objects", internal="`Slot::Channel(i)` per element", damf="header order", adm="`chna` -> ATU -> AT -> AS -> AC chain",
         evidence=f"{E['map']}, {E['ref']}", cls="MEASURED", structural="PASS", semantic="PASS", classification="",
         note="Every chna entry resolves through a unique UID/track/stream/channel chain to the audioObject that owns it; no dangling, duplicate or orphan node in any file ({inputs} inputs, {full_profile_findings} findings on the whole film)."),
    dict(feature="Object count and classification", source="OAMD program assignment (beds / ISF / dynamic)", internal="`Program {beds, isf_objects, dynamic_objects}`", damf="1:1", adm="1:1 for beds and dynamic objects; ISF absent",
         evidence=f"{E['batch']}, {E['har']} (C13)", cls="MEASURED", structural="PASS", semantic="PARTIAL", classification="ISF dropped silently (see ISF row)",
         note="Bed, dynamic-object and total element counts agree between OAMD, DAMF and ADM on every input (all corpus beds are LFE-only). Codec channels, JOC reconstructed signals, OAMD programme objects and ADM audioObjects are counted separately in the report."),
    dict(feature="Object identity over time", source="OAMD object index", internal="DAMF element id 10+k", damf="ID", adm="`Atmos_Obj_k` / `AO_100b+`, one channel format per object",
         evidence=f"{E['pcm']}, {E['time']}, {E['long']}", cls="MEASURED", structural="PASS", semantic="PASS", classification="",
         note="No object changes track or id through any programme: block tiling is gapless and sorted for every object (gaps {tiling_gaps}, overlaps {tiling_overlaps} on real material), and the PCM under each object's channel format is identical to the DAMF element from first to last sample."),
    dict(feature="X / Y coordinates", source="OAMD 6-bit codes (+ext precision), room 0..1", internal="`damf_position`: X=2x-1, Y=2(0.5-y)", damf="`pos`", adm="`position X/Y`, 10 decimals",
         evidence=f"{E['coord']}, {E['time']} (raw_oamd_crosscheck)", cls="MEASURED", structural="PASS", semantic="PASS", classification="",
         note="0 value mismatches at float32 precision over {matched_total} matched events; against the raw OAMD dump the mapping holds within {oamd_pos_max:.1e} (the dump's 4 decimals) on {oamd_clips} TrueHD clips. No axis swap, inversion, offset or clamp."),
    dict(feature="Z coordinate", source="OAMD 5-bit signed code, -1..1", internal="passed through", damf="`pos[2]`", adm="`position Z`, omitted when 0 (profile)",
         evidence=f"{E['coord']}", cls="MEASURED", structural="PASS", semantic="PASS", classification="omission = 0 per profile table 11",
         note="Absent Z is read as 0.0 by the profile rule; the comparator keeps presence separate from value and found no mismatch."),
    dict(feature="Distance", source="OAMD `object_distance` (unspecified / infinity / factor)", internal="parsed, no field in `ObjectState`", damf="no field", adm="none (profile forbids `absoluteDistance`; cartesian blocks)",
         evidence=f"{E['har']} (C19), {E['spec']}", cls="IMPLEMENTATION CHOICE", structural="PASS", semantic="N/T", classification="parsed but discarded; not representable in DAMF or in the profile; corpus never specifies it",
         note="Harness C19 pushes distance 2.0 and infinity through `Timeline::push`: nothing reaches DAMF or ADM and nothing is reported. The corpus carries `unspecified` only, so no real scene loses information today."),
    dict(feature="Gain", source="OAMD `object_gain` (dB / mute)", internal="`ObjectState.gain`", damf="`gain` dB", adm="omitted on active objects; `0.0` + importance `0` on inactive",
         evidence=f"{E['gain']}, {E['har']} (C02), {E['dolby']} (S2)", cls="MEASURED + REFERENCE", structural="PASS", semantic="FAIL", classification="avoidable loss: the profile text forbids it, Dolby's converters write it anyway",
         note="Harness C02: -6 dB, +3 dB, -inf and a mid-stream -12 dB change are all lost in oadec's ADM ({c02_loss_gain} losses, the change popped) while the PCM is unscaled - a muted active object becomes audible. Dolby's Conversion Tool and DEE write `<gain>` (linear) on {c02_ct_gain_blocks} active blocks for the same DAMF and emit a block for the gain change. On real material every gain is 0 dB, so no decoded stream is affected today."),
    dict(feature="Size (scalar)", source="OAMD `object_size` width", internal="`ObjectState.size` (one scalar)", damf="`size`", adm="`width`=`depth`=`height`",
         evidence=f"{E['har']} (C04), {E['dolby']} (S2)", cls="MEASURED", structural="PASS", semantic="PASS", classification="uniform size preserved; Dolby writes the same triple (+`diffuse 1`)",
         note="Uniform sizes 0.25/0.5/1.0 round-trip exactly in both oadec's and Dolby's ADM. The corpus never carries a non-zero size."),
    dict(feature="Width / height / depth (3-D size)", source="OAMD `object_size[3]` (width, depth, height)", internal="`size: r.size[0]` - first axis only (program.rs:242)", damf="one scalar (DAMF has no 3-axis size)", adm="three identical values (profile table 11 requires identical values)",
         evidence=f"{E['har']} (C04), {E['spec']}", cls="MEASURED", structural="PASS", semantic="PARTIAL", classification="collapse happens in the programme model, before both writers; the selected axis is an implementation choice; neither DAMF nor the profile can carry three axes",
         note="Harness C04 pushes size [0.2, 0.5, 0.8] through `Timeline::push`: DAMF and ADM carry only the first axis (DAMF sizes per object: {c04_sizes_text}), silently. Not representable downstream, but the choice of axis (first, not max or mean) and the silence are oadec's."),
    dict(feature="Divergence", source="OAMD extended-object `divergence`", internal="parsed, not carried", damf="no field", adm="none (profile: `objectDivergence` shall not be used)",
         evidence=f"{E['spec']}", cls="SPEC", structural="PASS", semantic="N/T", classification="not representable in DAMF or the profile; no corpus stream carries it",
         note="No test material exists and the authoring route cannot produce it; N/T, not PASS."),
    dict(feature="Importance / priority", source="OAMD `object_priority` (0..1, 1/32 steps)", internal="`ObjectState.importance`", damf="`importance`", adm="omitted on active objects (profile), `0` on inactive",
         evidence=f"{E['har']} (C03), {E['dolby']} (S3)", cls="MEASURED + REFERENCE", structural="PASS", semantic="PASS-TOL", classification="profile rule; Dolby drops it identically; corpus always 1.0",
         note="Harness C03 (importance 0.5 and 0.0 on active objects): {c03_loss_importance} losses in oadec's ADM; Dolby's converter writes importance on {s3_ct_imp_present} blocks for the same stimulus. Absent importance means 10 (BS.2076 default) = full priority, which equals the corpus value 1.0."),
    dict(feature="Interpolation mode", source="OAMD: linear ramp from the update time (TS 103 420 5.6.2)", internal="`ramp` samples", damf="`rampLength`", adm="`jumpPosition=1` always (profile)",
         evidence=f"{E['spec']}, {E['interp']}", cls="SPEC + MEASURED", structural="PASS", semantic="PASS", classification="same shape (ramp starting at the event) on both sides",
         note="BS.2076-3 section 9.3 and TS 103 420 figure 4 describe the same start-anchored ramp; the profile's `jumpPosition=1` is the right mode. The evaluator's self-check returns 0 against a synthetic ADM carrying the real ramps."),
    dict(feature="Interpolation length", source="OAMD `ramp_duration` (corpus: 1536, rare 32/480/1152/1472)", internal="`ramp`", damf="`rampLength` exact", adm="fixed: 0 on block 1, 250 samples afterwards (`INTERPOLATION_SAMPLES`)",
         evidence=f"{E['interp']}, {E['dolby']} (S1, reverse), {E['rend']}, {E['spec']} (table 11)", cls="SPEC + REFERENCE + MEASURED", structural="PASS", semantic="PASS-TOL", classification="profile rule (table 11 mandates 0 then 250); Dolby's converters write the same and Dolby's reader ignores any value; loss measured",
         note="{loss_ramp_total} of the matched real-material blocks carry 250 where the DAMF ramp was 1536 (or 32/1152/1472). Dolby's Conversion Tool and DEE write {s1_ct_interp_hist} for a stimulus cycling 0/32/250/480/1536/2048; every read-back through the Conversion Tool - of oadec's ADM, of a real-ramp variant and of Dolby's own ADM - returns rampLength 0 ({reverse_ramp_back[oadec-realramps]}). Metadata-domain deviation up to 1.67 room units within one block per event; rendered by EAR the fixed ramp costs, against a real-ramp variant of the same file, {render_realramp_sdr_text} (min SDR per layout), while oadec and Dolby render bit-identically ({render_ct_identical}/{render_ct_total} layout comparisons)."),
    dict(feature="Event timing (sample positions)", source="OAMD `sample_offset` + 32 x `block_offset_factor` + frame base", internal="`Event.sample_pos` (integer)", damf="`samplePos`", adm="`rtime` hh:mm:ss.fffff (10 us), `duration` rounded independently",
         evidence=f"{E['time']}, {E['long']}", cls="MEASURED", structural="PASS", semantic="PASS", classification="sample-exact recovery",
         note="Every ADM rtime decodes (nearest sample) to the DAMF samplePos: 0 time mismatches on {inputs} inputs incl. the whole film ({full_matched} matched, {full_defects} defects). {timecode_mismatch_total} of {timecodes_total} timecodes fail to re-encode to the identical string. Blocks tile without gaps in the sample domain; rtime and duration are rounded independently (10-us `tile_dec` histogram all 0 on real material)."),
    dict(feature="32 x block_offset_factor term", source="TS 103 420 clause 5.6.2", internal="`BLOCK_OFFSET_STEP = 32`", damf="kept", adm="kept",
         evidence=f"{E['time']} (raw_oamd_crosscheck)", cls="MEASURED", structural="PASS", semantic="PASS", classification="",
         note="Against oadec's raw OAMD dump: {oamd_damf_times_in} DAMF states and {oamd_adm_times_in} ADM blocks fall exactly on OAMD update times ({oamd_damf_times_out} / {oamd_adm_times_out} do not); {oamd_adm_blocks_on_bo32} ADM blocks sit on times that only exist with the +32 term ({oamd_bof1_updates} updates in the clips carry block_offset_factor 1)."),
    dict(feature="Start time / first block", source="first OAMD update", internal="first `Event`", damf="first event", adm="block 1 at 00:00:00.00000 (profile); synthetic when the first event is later",
         evidence=f"{E['har']} (C06), {E['dolby']} (S6)", cls="MEASURED + REFERENCE", structural="PASS", semantic="PASS-TOL", classification="corner case: real material always starts at 0; when it does not, oadec holds the first state from 0 and drops the real event (time lost), Dolby writes a default (0,0,0) block then the real event",
         note="Harness C06: {c06_classes}. Both behaviours invent something for a span DAMF leaves undefined; oadec's loses the arrival time of the first state. Not observed on any decoded stream."),
    dict(feature="Duration / end", source="programme length", internal="`frames`", damf="audio length", adm="last block ends at `frames`; audioProgramme end = frames",
         evidence=f"{E['time']}, {E['har']} (C07)", cls="MEASURED", structural="PASS", semantic="PASS-TOL", classification="one writer defect on synthetic input (Q): a block can run past the programme end",
         note="Real material: last block ends at the programme end for every object ({ends_at_frames_all}), programme span = frames, DAMF frames = ADM frames. Harness C07: an event past the end is dropped (fine) but the preceding block's duration is computed from it and overruns the end ({c07_tiling[overrun_objects]} object)."),
    dict(feature="Event density", source="up to 8 updates/object/frame", internal="`Timeline` dedup (`restates`)", damf="one event per change", adm="one block per event minus popped/superseded, plus synthetic",
         evidence=f"{E['time']}, {E['long']}", cls="MEASURED", structural="PASS", semantic="PASS-TOL", classification="ledger identity holds; ramp-only changes become duplicate blocks or are popped",
         note="`adm_blocks = states - superseded - beyond_end - trailing_popped - absorbed + synthetic` holds on every input. {inexpressible_total} duplicate blocks and {popped_total} trailing pops on real material, all ramp-only changes the profile cannot express. No coalescing, resampling or rate limiting."),
    dict(feature="ISF (intermediate spatial format)", source="OAMD `intermediate_spatial_format_idx`", internal="`Program.isf_objects` (TrueHD path hardcodes 0)", damf="`Slot::None` - audio and metadata dropped", adm="`Slot::None` - audio and metadata dropped",
         evidence=f"{E['har']} (C13)", cls="MEASURED", structural="PASS", semantic="FAIL", classification="silent drop; no diagnostic; no corpus stream carries ISF (N/T on real material)",
         note="Harness C13 (4 ISF objects between the bed and 2 objects): the ISF tones appear in no output track ({c13_tones}) and no warning is printed. On real material N/T; at the writer level a silent loss."),
    dict(feature="Bed events (time-varying bed gain/active)", source="OAMD bed object updates", internal="`BedState` events", damf="bed events kept", adm="none (profile: DirectSpeakers blocks have no rtime/duration)",
         evidence=f"{E['har']} (C05), {E['dolby']} (S8)", cls="MEASURED + REFERENCE", structural="PASS", semantic="PASS-TOL", classification="profile rule; Dolby's converters drop them identically; corpus beds never change",
         note="Harness C05: {c05_bed_lost} bed changes lost, LFE PCM unscaled; Dolby drops the same (S8, static bed gain -6 dB also ignored). {bed_changes_lost_total} bed changes lost on real material - none, because the LFE beds never change."),
    dict(feature="Bed configuration and speaker labels", source="OAMD bed channel assignment", internal="`bed_profile` (7.1.2 set only)", damf="named channels (Lss/Rss/Lrs/Rrs/...)", adm="`RC_*` labels + table-10 positions; other channels refused",
         evidence=f"{E['har']} (C14, C17, C21), {E['ref']}", cls="MEASURED", structural="PASS", semantic="PASS-TOL", classification="beds beyond 7.1.2 make `AdmWriter::create` fail explicitly (good), `Ls/Rs` of a 5.1 bed are labelled as side surrounds (untested on real material: all corpus beds are LFE-only)",
         note="C14: `{c14_error}` - an explicit failure, not a silent file. Zone rectangles equal the profile tables ({c17_findings} findings). The LFE-only conformed bed passes every profile rule; with `--no-bed-conform` the LFE-only set is not one of table 16's configuration sets - and neither is Dolby's own output for the same DAMF."),
    dict(feature="Object IDs with `--no-bed-conform`", source="-", internal="`AO_` + hex(0x1001+bed+k-1)", damf="-", adm="objects start below `AO_100b` when the bed has fewer than 10 channels",
         evidence=f"{E['har']} (C11, C12, C21b), {E['dolby']} (S11)", cls="MEASURED + REFERENCE", structural="FAIL", semantic="PASS", classification="profile table 17 violation; Dolby numbers objects from `AO_100b` regardless of bed size",
         note="C11 (no bed): {c11_findings}. The default 7.1.2 conform yields `AO_100b` and is clean; any smaller bed with conform off is not. Semantically harmless; structurally out of profile."),
    dict(feature="Sample rate", source="stream rate", internal="`sample_rate`", damf="`sampleRate`", adm="`audioTrackUID sampleRate` = stream rate; 250-sample constant scaled",
         evidence=f"{E['har']} (C15)", cls="MEASURED", structural="FAIL", semantic="PASS", classification="profile requires 48000 (table 23); a 96 kHz or 44.1 kHz programme is written without a warning",
         note="C15 (96 kHz): file written, interpolationLength 0.002604 s = 250 samples, findings {c15_findings}. No Atmos material at 96 kHz exists in the library; the 44.1 kHz Pi encode is the only real case (N/T for decoded output beyond the writer)."),
    dict(feature="Programme hierarchy (programme / content / object / pack)", source="-", internal="-", damf="`.atmos` presentation", adm="APR_1001 -> ACO_1001 -> AO_1001 (bed) + AO_100b.. (objects); custom DirectSpeakers pack AP_00011001; one Objects pack per object",
         evidence=f"{E['ref']}, {E['dolby']}", cls="MEASURED + REFERENCE", structural="PASS", semantic="PASS", classification="identical element inventory and ids to Dolby's converters on the same DAMF",
         note="Every produced ADM passes the reference-graph, chna and profile checks with zero findings (default conform)."),
    dict(feature="audioTrackUID / chna", source="-", internal="`ATU_` + (i+1)", damf="-", adm="one UID per PCM track; chna numTracks = numUIDs = channels",
         evidence=f"{E['map']}, {E['ref']}, {E['neg']} (M-A7, M-A13)", cls="MEASURED", structural="PASS", semantic="PASS", classification="",
         note="Chain verified on every file; the negative controls show a dangling trackRef and a wrong UID sample rate are caught."),
    dict(feature="axml (ADM XML)", source="-", internal="string building in `AdmWriter::finish`", damf="-", adm="ebuCore 2016 namespace, BS.2076-1 timecodes",
         evidence=f"{E['ref']}, {E['rend']}", cls="MEASURED + REFERENCE", structural="PASS", semantic="PASS", classification="well-formed, references complete, profile-conformant; the profile's audioStreamFormat double reference makes strict BS.2076 readers (EAR) refuse the file - Dolby's own files included",
         note="EAR renders only after the pack reference is removed from audioStreamFormat (applied identically to oadec's and Dolby's files); with that edit oadec and Dolby render bit-identically."),
    dict(feature="BW64 / RF64 structure", source="-", internal="RIFF + 28-byte JUNK -> ds64 when > 4 GiB", damf="-", adm="`RF64` FourCC, ds64 riffSize/dataSize/sampleCount, `fmt` tag 1 (24-bit), data, axml, chna, dbmd",
         evidence=f"{E['cont']}, {E['long']}", cls="MEASURED", structural="PASS", semantic="PASS", classification="RF64 (EBU Tech 3306) rather than the BS.2088 `BW64` FourCC; readers agree",
         note="Whole-film Pi: {full_bytes} bytes, {full_fourcc}, ds64 = {full_ds64}; ffprobe {full_ffprobe_frames}, bwf_info {full_bwf_frames}, ds64 sampleCount and the DAMF all give {full_frames} frames; {full_container_findings} container findings. Both size thresholds (data above 4 GiB; data below but RIFF above u32) promote to RF64 correctly (harness C22, C22b)."),
    dict(feature="dbmd chunk", source="-", internal="three verbatim Dolby segments + bed mask + LFE flags", damf="-", adm="required by Dolby validators; creator string gates acceptance",
         evidence=f"{E['dolby']} (validate)", cls="UNKNOWN / PROPRIETARY", structural="UNK", semantic="N/T", classification="opaque; Dolby's validators accept the tagged file",
         note="atmos_info 5.7.2 `--validate 1` and 1.1 accept oadec's ADM with `--dolby-origin-tag` (exit 0, no warnings) and refuse the default file on provenance only ('Content was not authored with Dolby tools'); bwf_info accepts both."),
    dict(feature="Same-position and out-of-order events", source="OAMD may restate at one time; the timeline counts out-of-order events", internal="`Timeline.out_of_order` counter", damf="written as they come", adm="same position: last wins (Dolby too); out of order: skipped state and overlapping blocks (R)",
         evidence=f"{E['har']} (C08, C09), {E['dolby']} (S13)", cls="MEASURED + REFERENCE", structural="PASS", semantic="PASS-TOL", classification="R is a writer defect on hypothetical input; 0 out-of-order events on every decoded stream",
         note="C09: {c09_tiling}. The writer never sorts; the CLI counts out-of-order events and reported 0 on every input of this audit."),
    dict(feature="`--presentation` for ADM/DAMF", source="-", internal="forced to 3 (`cli/damf.rs:205`)", damf="-", adm="-",
         evidence="prior audit row; not re-measured", cls="INFERRED", structural="PASS", semantic="N/T", classification="flag silently ignored (unchanged since the previous audit)", note=""),
    dict(feature="Diagnostics and exit codes", source="-", internal="`oadec-spatial` has no logging", damf="-", adm="no warning for any dropped semantic; exit 0/2/7 reflect the bitstream only",
         evidence=f"{E['har']}, {E['batch']}", cls="MEASURED", structural="PASS", semantic="FAIL", classification="silent lossy conversion",
         note="None of ramp, gain, importance, 3-D size, ISF, bed events, non-48 kHz or out-of-order input produce a diagnostic; the only ADM-time failure is the unsupported bed channel (C14). Head cuts exit 7 for the truncated last access unit and the 96 kHz non-Atmos clip exits 2, both correctly."),
    dict(feature="Negative controls", source="-", internal="-", damf="-", adm="-",
         evidence=f"{E['neg']}", cls="MEASURED", structural="PASS", semantic="PASS", classification="tool validation",
         note="{neg_fired} of {neg_total} injected defects fired the intended detector with no specificity violation ({neg_specificity}); not testable on this material: {neg_nt} (no inactive block in pi-head50m; covered by harness C16)."),
    dict(feature="Renderer interoperability", source="-", internal="-", damf="-", adm="-",
         evidence=f"{E['rend']}, {E['dolby']} (validate)", cls="REFERENCE", structural="PASS", semantic="PASS-TOL", classification="Dolby validators: accepted (tagged); EAR: accepted after the profile's stream-format edit; Dolby Atmos Renderer not available",
         note="EAR speaker outputs of oadec's ADM and Dolby's Conversion-Tool ADM are sample-identical in {render_ct_identical} of {render_ct_total} layout comparisons over {render_scenes}. Dolby's DRP cannot open ADM or DAMF files, and no Dolby Atmos Renderer is installed, so section 26/27 rest on the Conversion Tool, DEE, atmos_info, bwf_info and EAR."),
]

SCORES = [
    dict(name="PCM fidelity", value="100", basis="{pcm_identical}/{pcm_pairs} track pairs sample-identical, whole film included"),
    dict(name="Object mapping", value="100", basis="chna chain and pairing matrix confirmed on every input; identity stable over time"),
    dict(name="Bed mapping", value="90", basis="LFE beds exact; multi-channel beds only via harness (labels/positions per table 10 confirmed); 5.1 `Ls/Rs` labelling untested on real material"),
    dict(name="Coordinate fidelity", value="100", basis="0 mismatches at float32 precision; raw-OAMD mapping within {oamd_pos_max:.1e}"),
    dict(name="Gain fidelity", value="40", basis="real material unaffected (all 0 dB); writer drops non-zero gains and mutes that Dolby's converters keep (harness C02)"),
    dict(name="Size fidelity", value="70", basis="uniform size exact; three-axis size collapsed to the first axis in the model (C04); corpus never carries size"),
    dict(name="Timing fidelity", value="100", basis="sample-exact against DAMF and raw OAMD incl. the +32 term; 0 drift over 1:24:08"),
    dict(name="Interpolation fidelity", value="50", basis="mode right, length fixed at 250 by the profile; identical to Dolby; rendered loss against real ramps {render_realramp_sdr_text}"),
    dict(name="ADM structural validity", value="95", basis="0 findings on every default-conform file; `--no-bed-conform` object IDs and non-48 kHz files violate the profile silently"),
    dict(name="ADM semantic fidelity", value="80", basis="everything the profile can carry is carried exactly; what it cannot (ramp, bed events, importance) is lost silently; gain and ISF are lost avoidably"),
    dict(name="Renderer interoperability", value="85", basis="Dolby validators accept (tagged); EAR bit-identical to Dolby after the profile-conflict edit; no Dolby Atmos Renderer available"),
    dict(name="Overall ADM export", value="82", basis="a faithful Dolby-profile ADM of the decoded scene, equal to Dolby's own conversion, with the profile's losses undeclared and three writer-level defects on inputs the corpus never produces"),
]

VERDICTS = {
    "Structural ADM verdict": "MOSTLY VALID. Every default (bed-conformed, 48 kHz) file passes the container, reference-graph, chna and Dolby Atmos Master ADM profile v1.0 checks and Dolby's own validators (with the origin tag); `--no-bed-conform` object IDs and non-48 kHz programmes leave the profile without a warning.",
    "Atmos semantic fidelity verdict": "MINOR SEMANTIC LOSS on every decoded stream tested: PCM, positions, timing and identity are exact and the file is functionally identical to Dolby's own DAMF-to-ADM conversion; the only loss on real material is the profile's fixed 250-sample ramp. For scenes the corpus does not contain (non-zero gain, ISF, 3-D size, bed events, importance) the output would be STRUCTURALLY VALID BUT SEMANTICALLY INCOMPLETE, and nothing tells the user.",
}
