[package]
name = "oadec-joc"
description = "Joint Object Coding object reconstruction (QMF domain)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
oadec-emdf.workspace = true
thiserror.workspace = true
[lints]
workspace = true
