#!/usr/bin/env python3
"""Generate the JOC Huffman trees and the QMF prototype window as Rust source.

The tables are the ones ETSI ships next to TS 103 420 V1.2.1 in
`ts_103420v010201p0.zip` (file `ts_103420_tables.c`). They are format data:
the Huffman trees of Annex A.1 and the 640-tap window QWIN of clause 7.4.

    python tools/gen_joc_tables.py path/to/ts_103420_tables.c

writes `crates/oadec-emdf/src/joc_tables.rs` and
`crates/oadec-joc/src/qmf_window.rs` relative to the repository root.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

TREES = [
    ("joc_huff_code_coarse_generic", "COARSE_MTX", "Mode 0, type MTX (table A.1)"),
    ("joc_huff_code_fine_generic", "FINE_MTX", "Mode 1, type MTX (table A.2)"),
    ("joc_huff_code_coarse_coeff_sparse", "COARSE_VEC", "Mode 0, type VEC (table A.3)"),
    ("joc_huff_code_fine_coeff_sparse", "FINE_VEC", "Mode 1, type VEC (table A.4)"),
    ("joc_huff_code_5ch_pos_index_sparse", "IDX_5CH", "Mode 5, type IDX (table A.5)"),
    ("joc_huff_code_7ch_pos_index_sparse", "IDX_7CH", "Mode 7, type IDX (table A.6)"),
]


def parse_int_table(src, name):
    m = re.search(r"const int %s\[\]\[2\] =\s*\{(.*?)\};" % re.escape(name), src, re.S)
    if not m:
        sys.exit(f"table {name} not found")
    pairs = re.findall(r"\{\s*(-?\d+)\s*,\s*(-?\d+)\s*\}", m.group(1))
    return [(int(a), int(b)) for a, b in pairs]


def parse_float_table(src, name):
    m = re.search(r"const float %s\[(\d+)\] =\s*\{(.*?)\};" % re.escape(name), src, re.S)
    if not m:
        sys.exit(f"table {name} not found")
    n = int(m.group(1))
    values = re.findall(r"([+-]?\d+\.\d+e[+-]\d+)f", m.group(2))
    if len(values) != n:
        sys.exit(f"{name}: expected {n} values, found {len(values)}")
    return values


def check_tree(name, nodes):
    """Every internal node index must point forward; every leaf value must be
    reachable exactly once; the leaf values must be a contiguous 0..k range."""
    leaves = []
    for i, (a, b) in enumerate(nodes):
        for v in (a, b):
            if v > 0:
                if v >= len(nodes):
                    sys.exit(f"{name}: node {i} points past the table")
            elif v == 0 and i != 0:
                sys.exit(f"{name}: node {i} points back to the root")
            else:
                leaves.append(-v - 1)
    leaves.sort()
    if leaves != list(range(len(leaves))):
        sys.exit(f"{name}: leaf values are not 0..{len(leaves) - 1}: {leaves[:8]}...")
    return len(leaves)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    src = pathlib.Path(sys.argv[1]).read_text()

    out = [
        "//! JOC Huffman trees of ETSI TS 103 420 V1.2.1, Annex A.1.",
        "//!",
        "//! Generated by `tools/gen_joc_tables.py` from the table file ETSI ships",
        "//! with the specification (`ts_103420v010201p0.zip`). Each entry is a",
        "//! node `[child_for_bit_0, child_for_bit_1]`; a positive child is the",
        "//! index of the next node, a non-positive child `c` is the leaf value",
        "//! `-c - 1` (clause 6.6.3).",
        "",
    ]
    for cname, rname, doc in TREES:
        nodes = parse_int_table(src, cname)
        count = check_tree(cname, nodes)
        out.append(f"/// {doc}: {count} values, {len(nodes)} nodes.")
        out.append(f"pub const {rname}: [[i16; 2]; {len(nodes)}] = [")
        line = "   "
        for a, b in nodes:
            item = f" [{a}, {b}],"
            if len(line) + len(item) > 96:
                out.append(line)
                line = "   "
            line += item
        out.append(line)
        out.append("];")
        out.append("")
    (ROOT / "crates/oadec-emdf/src/joc_tables.rs").write_text("\n".join(out), newline="\n")

    values = parse_float_table(src, "prot64")
    out = [
        "//! The 640-tap prototype window of the 64-band complex QMF bank",
        "//! (ETSI TS 103 420 V1.2.1, clause 7.4, table QWIN).",
        "//!",
        "//! Generated by `tools/gen_joc_tables.py` from the table file ETSI ships",
        "//! with the specification (`ts_103420v010201p0.zip`).",
        "",
        "/// Window coefficients, index `j` of clauses 7.2 and 7.3.",
        f"pub const QWIN: [f64; {len(values)}] = [",
    ]
    for i in range(0, len(values), 4):
        out.append("    " + " ".join(f"{v}," for v in values[i : i + 4]))
    out.append("];")
    out.append("")
    (ROOT / "crates/oadec-joc/src/qmf_window.rs").write_text("\n".join(out), newline="\n")
    print("wrote joc_tables.rs and qmf_window.rs")


if __name__ == "__main__":
    main()
