#!/usr/bin/env python3
"""Generate the AHT vector quantization tables (ETSI TS 102 366 V1.4.1, clause
E.3, tables E.3.1 to E.3.7) as Rust source from the text of the specification.

    python tools/gen_vq_tables.py path/to/ts_102366v010401p.txt

writes `crates/oadec-eac3/src/vq.rs`. The tables are format data: each entry is
a vector of six 16-bit two's complement mantissas indexed by the code word of
the corresponding `hebap` (2 to 9 bits).
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SIZES = {1: 4, 2: 8, 3: 16, 4: 32, 5: 128, 6: 256, 7: 512}


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    text = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8", errors="replace")
    start = text.rindex("E.3 AHT vector quantization tables")
    end = text.index("Annex F", start)
    section = text[start:end]
    tables = {}
    current = None
    row = re.compile(r"^(\d+)\s+(0x[0-9a-fA-F]{4})\s+(0x[0-9a-fA-F]{4})\s+(0x[0-9a-fA-F]{4})\s+(0x[0-9a-fA-F]{4})\s+(0x[0-9a-fA-F]{4})\s+(0x[0-9a-fA-F]{4})\s*$")
    for line in section.splitlines():
        m = re.match(r"^Table E\.3\.(\d+): VQ table for hebap (\d+)", line)
        if m:
            current = int(m.group(2))
            tables[current] = {}
            continue
        m = row.match(line.strip())
        if m and current is not None:
            idx = int(m.group(1))
            vals = [int(v, 16) for v in m.groups()[1:]]
            if idx in tables[current]:
                sys.exit(f"hebap {current}: duplicate index {idx}")
            tables[current][idx] = vals
    out = [
        "//! AHT vector quantization tables of ETSI TS 102 366 V1.4.1, clause E.3",
        "//! (tables E.3.1 to E.3.7), generated by `tools/gen_vq_tables.py` from the",
        "//! text of the specification. Each entry is the six-block mantissa vector",
        "//! selected by a code word of `HEBAP_BITS[hebap]` bits; values are 16-bit",
        "//! two's complement fractions.",
        "",
    ]
    for hebap in range(1, 8):
        rows = tables.get(hebap, {})
        n = SIZES[hebap]
        if sorted(rows) != list(range(n)):
            missing = [i for i in range(n) if i not in rows]
            sys.exit(f"hebap {hebap}: expected {n} rows, got {len(rows)}; missing {missing[:10]}")
        out.append(f"/// Table E.3.{hebap}: `hebap` {hebap}, {n} vectors.")
        out.append(f"pub const VQ{hebap}: [[i16; 6]; {n}] = [")
        for i in range(n):
            vals = ", ".join(f"{v - 65536 if v >= 32768 else v}" for v in rows[i])
            out.append(f"    [{vals}],")
        out.append("];")
        out.append("")
    out.append("/// The vector table of a `hebap` in `1..=7`.")
    out.append("#[must_use]")
    out.append("pub fn table(hebap: u8) -> &'static [[i16; 6]] {")
    out.append("    match hebap {")
    for hebap in range(1, 8):
        out.append(f"        {hebap} => &VQ{hebap},")
    out.append("        _ => &[],")
    out.append("    }")
    out.append("}")
    out.append("")
    (ROOT / "crates/oadec-eac3/src/vq.rs").write_text("\n".join(out), newline="\n")
    print("wrote vq.rs:", {k: len(v) for k, v in sorted(tables.items())})


if __name__ == "__main__":
    main()
